insert into playlist values('test1', 1);
update song set hit=hit+1 where songId=1 ;
insert into playlist values('test1', 3);
update song set hit=hit+1 where songId=3;
insert into playlist values('test1', 6);
update song set hit=hit+1 where songId=6;
insert into playlist values('test1', 10);
update song set hit=hit+1 where songId=10;
insert into playlist values('test1', 25);
update song set hit=hit+1 where songId=25;
insert into playlist values('test1', 27);
update song set hit=hit+1 where songId=27;
insert into playlist values('test1', 33);
update song set hit=hit+1 where songId=33;
insert into playlist values('test1', 41);
update song set hit=hit+1 where songId=41;
insert into playlist values('test1', 55);
update song set hit=hit+1 where songId=55;
insert into playlist values('test1', 56);
update song set hit=hit+1 where songId=56;
insert into playlist values('test1', 22);
update song set hit=hit+1 where songId=22;
insert into playlist values('test1', 30);
update song set hit=hit+1 where songId=30;
insert into playlist values('test2', 1);
update song set hit=hit+1 where songId=1;
insert into playlist values('test2', 2);
update song set hit=hit+1 where songId=2;
insert into playlist values('test2', 4);
update song set hit=hit+1 where songId=4;
insert into playlist values('test2', 8);
update song set hit=hit+1 where songId=8;
insert into playlist values('test2', 16);
update song set hit=hit+1 where songId=16;
insert into playlist values('test2', 32);
update song set hit=hit+1 where songId=32;
insert into playlist values('test2', 64);
update song set hit=hit+1 where songId=64;
insert into playlist values('test2', 9);
update song set hit=hit+1 where songId=9;
insert into playlist values('test2', 18);
update song set hit=hit+1 where songId=18;
insert into playlist values('test2', 27);
update song set hit=hit+1 where songId=27;
insert into playlist values('test2', 36);
update song set hit=hit+1 where songId=36;
insert into playlist values('test2', 45);
update song set hit=hit+1 where songId=45;
insert into playlist values('test2', 48);
update song set hit=hit+1 where songId=48;
insert into playlist values('test2', 51);
update song set hit=hit+1 where songId=51;
insert into playlist values('test3', 6);
update song set hit=hit+1 where songId=6;
insert into playlist values('test3', 12);
update song set hit=hit+1 where songId=12;
insert into playlist values('test3', 18);
update song set hit=hit+1 where songId=18;
insert into playlist values('test3', 24);
update song set hit=hit+1 where songId=24;
insert into playlist values('test3', 30);
update song set hit=hit+1 where songId=30;
insert into playlist values('test3', 36);
update song set hit=hit+1 where songId=36;
insert into playlist values('test3',42);
update song set hit=hit+1 where songId=42;
insert into playlist values('test3', 48);
update song set hit=hit+1 where songId=48;
insert into playlist values('test3', 54);
update song set hit=hit+1 where songId=54;
insert into playlist values('test4', 5);
update song set hit=hit+1 where songId=5;
insert into playlist values('test4', 10);
update song set hit=hit+1 where songId=10;
insert into playlist values('test4', 15);
update song set hit=hit+1 where songId=15;
insert into playlist values('test4', 20);
update song set hit=hit+1 where songId=20;
insert into playlist values('test4', 25);
update song set hit=hit+1 where songId=25;
insert into playlist values('test4', 30);
update song set hit=hit+1 where songId=30;
insert into playlist values('test4', 65);
update song set hit=hit+1 where songId=65;
insert into playlist values('test4', 35);
update song set hit=hit+1 where songId=35;
insert into playlist values('test4', 40);
update song set hit=hit+1 where songId=40;
insert into playlist values('test4', 45);
update song set hit=hit+1 where songId=45;
insert into playlist values('test4', 50);
update song set hit=hit+1 where songId=50;
insert into playlist values('test4', 55);
update song set hit=hit+1 where songId=55;
insert into playlist values('test5', 12);
update song set hit=hit+1 where songId=12;
insert into playlist values('test5', 24);
update song set hit=hit+1 where songId=24;
insert into playlist values('test5', 36);
update song set hit=hit+1 where songId=36;
insert into playlist values('test5', 48);
update song set hit=hit+1 where songId=48;
insert into playlist values('test5', 60);
update song set hit=hit+1 where songId=60;
insert into playlist values('test6', 1);
update song set hit=hit+1 where songId=1;
insert into playlist values('test6', 10);
update song set hit=hit+1 where songId=10;
insert into playlist values('test6', 20);
update song set hit=hit+1 where songId=20;
insert into playlist values('test6', 30);
update song set hit=hit+1 where songId=30;
insert into playlist values('test6', 40);
update song set hit=hit+1 where songId=40;
insert into playlist values('test6', 50);
update song set hit=hit+1 where songId=50;
insert into playlist values('test6', 60);
update song set hit=hit+1 where songId=60;
insert into playlist values('test7', 1);
update song set hit=hit+1 where songId=1;
insert into playlist values('test7', 11);
update song set hit=hit+1 where songId=11;
insert into playlist values('test7', 21);
update song set hit=hit+1 where songId=21;
insert into playlist values('test7', 31);
update song set hit=hit+1 where songId=31;
insert into playlist values('test7', 41);
update song set hit=hit+1 where songId=41;
insert into playlist values('test7', 51);
update song set hit=hit+1 where songId=51;
insert into playlist values('test7', 61);
update song set hit=hit+1 where songId=61;
insert into playlist values('test8', 2);
update song set hit=hit+1 where songId=2;
insert into playlist values('test8', 22);
update song set hit=hit+1 where songId=22;
insert into playlist values('test8', 32);
update song set hit=hit+1 where songId=32;
insert into playlist values('test8', 42);
update song set hit=hit+1 where songId=42;
insert into playlist values('test8', 52);
update song set hit=hit+1 where songId=52;
insert into playlist values('test8', 62);
update song set hit=hit+1 where songId=62;
insert into playlist values('test9', 7);
update song set hit=hit+1 where songId=7;
insert into playlist values('test9', 14);
update song set hit=hit+1 where songId=14;
insert into playlist values('test9', 21);
update song set hit=hit+1 where songId=21;
insert into playlist values('test9', 28);
update song set hit=hit+1 where songId=28;
insert into playlist values('test9', 35);
update song set hit=hit+1 where songId=35;
insert into playlist values('test9', 42);
update song set hit=hit+1 where songId=42;
insert into playlist values('test9', 49);
update song set hit=hit+1 where songId=49;
insert into playlist values('test9', 56);
update song set hit=hit+1 where songId=56;
insert into playlist values('test9', 63);
update song set hit=hit+1 where songId=63;
