insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '누구 없소', '이하이');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사랑에 연습이 있다면', '임재현');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '너에게 못했던 내 마지막 말은', '다비치');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '2002', 'Anne-Marie');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '작은 것들을 위한 시', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'bad guy', 'Billie Eilish');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '주저하는 연인들을 위해', '잔나비');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'AH YEAH', 'WINNER');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'FANCY', 'TWICE');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Goodbye', '박효신');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '노래방에서', '장범준');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사계', '태연');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '나만, 봄', '볼빨간사춘기');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사월이 지나면 우리 헤어져요', '첸');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '그때가 좋았어', '케이시');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '소우주', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Kill This Love', 'BLACKPINK');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '봄날', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사랑이 식었다고 말해도 돼', '먼데이 키즈');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Make It Right', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '대충 입고 나와', '우디');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '별 보러 갈래?', '볼빨간사춘기');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'IDOL', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사계', '엠씨더맥스');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '교통정리', '기리보이');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '달라달라', 'ITZY');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '옥탑방', '엔플라잉');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Dionysus', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '모든 날, 모든 순간', '폴킴');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '당신과는 천천히', '장범준');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'HOME', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Jamais Vu', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Paris In The Rain', 'Lauv');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '넘쳐흘러', '엠씨더맥스');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '너를 만나', '폴킴');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '비가 오잖아', '소유');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '벌써 12시', '청하');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '진심이 담긴 노래', '케이시');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '다섯 번째 계절', '오마이걸');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Intro : Persona', '방탄소년단');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '오늘 밤에', '홍진영');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '비올레타', 'IZ*ONE');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '니 소식', '송하예');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Love Shot', 'EXO');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL,'안녕하세요', '김재환');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '7 rings', 'Ariana Grande');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '이 노래가 클럽에서 나온다면', '우디');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '돈 Call Me', '염따');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Way Back Home', '숀');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '고고베베', '마마무');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '사랑에 연습이 있었다면 (답가)', '히키');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '오월의 어느 봄날', '임한별');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '멍청이', '화사');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '이별하러 가는 길', '임한별');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '술이 달다', '에픽하이');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'comethru', 'Jeremy Zucker');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '신용재', '하은');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '눈', '강현준');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'Speechless', 'Naomi Scott');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '180도', '벤');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '초록빛', '폴킴');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'BREATHE', 'AB6IX');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'YES or YES', 'TWICE');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '봄', '박봄');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, 'thank u, next', 'Ariana Grande');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '신청곡', '이소라');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '불면', '오반');
insert into song(songId, title, artist) values(seq_songId.NEXTVAL, '이 밤', '양다일');
